### PR TITLE
Added ability for install, uninstall and upgrade subcommands to take …

### PR DESCRIPTION
**Pull request by felixlevert**
…multiple pims as arguments

## Proposed Changes
Enables users to install/uninstall/upgrade multiple pims with one command.
Examples:
`packageless install python dotnet git`

`packageless uninstall python dotnet git`

## Type of Change
What kind of change to **packageless** is this?

- [ ] Bug Fix
- [x] Feature
- [ ] Documentation
- [ ] Repository Enhancement
- [ ] Testing

## Checklist
Before the Pull Request can be considered for merging, the following Checklist should have the corresponding fields completed:

- [x] All tests have passed locally after running `go test ./...`
- [x] I have added tests that prove my fix or feature works as expected
- [ ] I have added any necessary documentation for my fix or feature

## Comments
I believe this to be the cleanest approach to implementing this feature without making fairly large changes to the individual subcommand's Run methods. The part I don't love about this approach is that it introduces subcommand specific logic into the generic subcommand interface. I am open to suggestions on a better approach!

### CODE REVIEW

**Review by everettraven — COMMENTED** [review]
@felixlevert great work on this solution, and thank you for taking the time to contribute!

Would you mind adding a test case (or multiple if needed) to test that this is working as expected when more than one pim name is provided?

**Comment by felixlevert** [comment]
@everettraven Absolutely! Just added some and committed the changes to this PR. 

Disclaimer, this is one of my first times writing unit tests so criticism is welcome :)

**Comment by everettraven** [comment]
@felixlevert the tests look great! I will resolve the merge conflicts tonight to get the automated tests to run. If those check out then I will go ahead and merge your changes in. Thanks so much for your contribution!

**Review by everettraven — APPROVED** [review]

**Comment by felixlevert** [comment]
Thank you! Hopefully I can contribute more in the future, this is a cool project.

**Comment by everettraven** [comment]
> Thank you! Hopefully I can contribute more in the future, this is a cool project.

@felixlevert Thanks, I'm glad to hear you like the project! I hope you are able to contribute more in the future as well. I am currently in the process of creating a todo list of stuff that needs to be done for the project and then converting them into issues. Keep an eye out on this repository, [packageless-containers](https://github.com/everettraven/packageless-containers), and [packageless-pims](https://github.com/everettraven/packageless-pims) and you may find some more issues to tackle

**Comment by everettraven** [comment]
closes #50

**Pull request merged**
